### ISSUE TITLE
is it possible to have an option like filenameMin with a rev tag included

### ISSUE THREAD

**Issue by khanhlu2013** [OverZealous/gulp-cdnizer#10]
It would be nice in this example below to have a rev tag included in the cdn. However filenameMin does not include rev tag
            {
                file: '{{STATIC_URL}}dist/product_app-????????.js',
                cdn: '{{STATIC_URL}}dist/${ filenameMin }'
            }

**Comment by OverZealous** [comment]
The property `filename` includes the file name unaltered.  `filenameMin` is only necessary when you are using a public CDN where the file has a `.min` inserted in it, but your local copy does not.

You can also use `filepathRel` for the complete path (with no leading slash), unaltered (so, your `cdn` would be `'{{STATIC_URL}}${filepathRel}'`).

[The complete options for `cdn` are in the README.](https://github.com/OverZealous/gulp-cdnizer#optionsfilescdn)

**Comment by khanhlu2013** [comment]
like you said, filename and filepathRel is a better choice for me. However in my case, i use a minify version of the filename in my cdn. So how do i add a ".min" to the filename right before the file extension. I imagine something like this:

{
file: '{{STATIC_URL}}dist/product_app-????????.js',
cdn: '{{STATIC_URL}}dist/${ filenameWithoutExtension }.min.js'
}

**Comment by khanhlu2013** [comment]
I found another alternative: using minify for both local development and cdn (with sourcemap)

{
file: '{{STATIC_URL}}dist/product_app-????????.min.js',
cdn: '{{STATIC_URL}}dist/${ filename }'
}
