### ISSUE TITLE
Version not being pulled from .bower.json

### ISSUE THREAD

**Issue by jonfaulkenberry** [OverZealous/gulp-cdnizer#11]
I am using the Bower package aws-sdk-js and it does not specify the version in it's bower.json. However, the version is specified in it's .bower.json. The tool does not seem to work with this configuration.

**Comment by OverZealous** [comment]
I don't really know the difference between bower.json and the dotfile.  (Or, for that matter, why there are two supported solutions.)

cdnizer looks first for a `bower.json` and then a `.bower.json` file to find the version.  I suppose I can correct this by loading the file and then checking to see if the version property is set.

(As far as I can tell, this really means that `aws-sdk-js` is incorrect, and you should file a separate bug with them as well.)

**Comment by jonfaulkenberry** [comment]
The ` .bower.json` file is metadata generated by Bower itself. The issue (I believe) is that cdnizer is not pulling the version string from the "version" property of the `.bower.json` as cdnizer's README states.

It is indeed the fault of the Bower package provider that the version is omitted, but if someone as big as Amazon is committing this type of error with their AWS libraries, it could be fairly common. Would be nice if cdnizer could get around this and just use the installed version if no version is specified in `bower.json`.

:+1:  Thanks for looking into this so quickly.

**Comment by OverZealous** [comment]
It was simply looking for a `bower` file, finding that, and stopping there.  I've almost got a fix in place, it will check more specifically for a version string, rather than just the file itself.

**Comment by OverZealous** [comment]
The nice thing about this catch is that cdnizer now correctly throws an Error if there is a `bower.json` (and/or `.bower.json`) with no version set.

Thanks for reporting this.

**Comment by jonfaulkenberry** [comment]
Yes, the issue is fixed with 1.1.2. Thanks again :+1:
