### ISSUE TITLE
Img src using underscore templates

### ISSUE THREAD

**Issue by affemaen** [OverZealous/gulp-cdnizer#12]
There is an issue cdnizing underscore templates if img src contains a '%'. Using version 1.1.2

`<img src=<%=imageUrl%> />`

or

`<img src="<%=imageUrl%>" />`

Example cdnize usage

`
gulp.task('test', function() {
  return gulp.src('./dir/example.html)
    .pipe(cdnizer({
      defaultCDNBase: cdn,
      files: ['**/*.{gif,png,jpg,jpeg,svg}'],
    }))
    .pipe(gulp.dest(someDir));
});
`

>{ [Error: URIError: URI malformed ]
  message: 'URIError: URI malformed',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-cdnizer',
  __safety: { toString: [Function] } }

**Comment by OverZealous** [comment]
What's the use case here?  cdnizer is intended to be run _after_ all your files have been processed, so there shouldn't be templating information in files being passed into it.

**Comment by affemaen** [comment]
We have a Single Page Backbone.js application. The templates are preprocessed and collected into a .js file during build time. The templates are later processed in the clients and populated with data. We want all static image sources to be fetched from a cdn and replaced during build time. We are not trying to process the template data inside the img tag only the static content.

**Comment by OverZealous** [comment]
OK.  Well, I'm busy now, so I don't know if I can get to this right away, but feel free to create a PR.  The issue is on [OverZealous/cdnizer](https://github.com/OverZealous/cdnizer), not gulp-cdnizer, and should be a relatively simple try/catch around the URI processing.

**Comment by OverZealous** [comment]
Just pushed a new version, you should be all set.
