### ISSUE TITLE
All script tag after "text/javascript" are not replaced

### ISSUE THREAD

**Issue by barisbikmaz** [OverZealous/gulp-cdnizer#13]
if I have a script tag like this 
```javascript
<script type="text/javascript">
...
</script>
```
all following script tags are not "cdnized".

This way works:
```javascript
<script>
...
</script>
```

**Comment by OverZealous** [comment]
I was unable to duplicate this issue in a test.  Can you provide me with a minimal failing test?  I would like an input, output, and the arguments passed to `cdnizer`.

(As an aside, the issue would be with `cdnizer` itself, not `gulp-cdnizer`.)

**Comment by barisbikmaz** [comment]
Sorry for the inconvenience. Magically everything is working now. Can't reproduce it anymore. Must be a failure of mine..

**Comment by OverZealous** [comment]
No inconvenience, I just added another test case in.  Glad it's working for you now!
