### ISSUE TITLE
img tag src is parsed wrong

### ISSUE THREAD

**Issue by snoepkast** [OverZealous/gulp-cdnizer#15]
Original:
```html
<html>
    <img class="img-responsive" alt="" src="/some/source.png">
</html>
```

Result:
```html
<html>
    <img class="img-responsive" alt="" src=myCDN/"myCDN/some/source.png">
</html>
```

Task:
```js
gulp.task('templates', [], function() {
    return gulp.src('frontend/app/**/*.html')
        .pipe(cdnizer({
            defaultCDNBase:'myCDN',
            files: [
                '**/*.*'
            ]
        }))
        .pipe(gulp.dest('some/buildDir/'))
});
```

Maybe I'm doing something wrong, since I don't get any results at all if I don't use the wildcard files blob (why do we have to pass that to cdnizer? Doesn't it get the file stream from the pipe?), but basically it adds the cdn url two times (one time in the ""s and one time before).

I've also tested it with some css files and those work like intended with this setup.

**Comment by OverZealous** [comment]
You have to specify the file patterns you want replaced by the CDN—it does _not_ use the gulp stream (the stream is the HTML file, not the file patterns it's going to replace).

You should be more specific in your file pattern, as in the examples in the documentation.  You've basically told it to replace anything that might be a file reference (and src, url, whatever) with your CDN, which is almost certainly not what you mean.

This pattern, from the docs, is good for images:

```js
files: ['**/*.{gif,png,jpg,jpeg}']
```

**Comment by snoepkast** [comment]
That did the trick, thanks for clearing that up for me :+1:
