### ISSUE TITLE
Can't get cdnizer to recognize paths where rev comes after .min.

### ISSUE THREAD

**Issue by regularmike** [OverZealous/gulp-cdnizer#17]
If I'm using gulp-rev with an already-minified file, e.g. jquery.min.js, it will create something like the following:

`jquery.min-4a356126b9.js`

I would expect that if I set `allowRev` to `true` and use `jquery.min.js` for `file` that it would pick it up, but it ignores it. I tried `jquery.js` with `allowRev` and `allowMin` both set to `true`, but that doesn't work because .min is supposed to appear after the rev.

In fact, it seems like `allowRev` doesn't work whenever I have more than one dot in the filename, e.g. `jquery.foo.bar-4a356126b9.js` doesn't seem to be recognized when specifying `jquery.foo.bar.js` for `file` and setting `allowRev` to `true` . Am I missing something?

My current workaround is just to use `jquery.min-*.js`, which works fine. Just thought I'd mention it.

**Comment by OverZealous** [comment]
As the docs say, it's simple functionality.  You can easily override the feature by setting `allowRev` to `false` and adding your own patterns in to your glob patterns:

https://github.com/OverZealous/gulp-cdnizer#optionsallowrev

**Comment by regularmike** [comment]
Yeah, it works fine for me with the glob patterns. I was just confused at first. Would you be interested in a pull request to add support for files with dots in the name. If not, I could create a pull request for updating the docs to mention that you should use the glob pattern if you have something like jquery.easing-<rev>.js.

**Comment by OverZealous** [comment]
If you would like to create a PR, that is fine, just make sure it's pretty thoroughly tested.

The issue I have is that I don't see why the `rev` pattern would ever be before the `.min`.  You should _always_ perform the revisioning as the last modification step of your process.  This guarantees that the file is in it's final state, and that the hash value makes sense.  If you, for example, revision before the file is minified, but the minification process changes the content in a different way (due to, for example, updates to the minification engine), then your hash will be the same for two different file contents.

**Comment by regularmike** [comment]
I totally agree. I was trying to get it to work with something like `jquery.min-4a356126b9.js`. I was quoting the readme when I said ".min is supposed to appear after the rev." The readme says this under `allowMin`: "Allow for file names that optionally have .min inserted before the file extension (*but after rev, if enabled*)." That seems to be different than what you're talking about above. Or am I reading that wrong?

**Comment by OverZealous** [comment]
Oh, yeah, you are right, it does say that.  Honestly, I haven't done much work on this repo in a while.  I think the idea with the rev/min was that you could reference the pre-minified, non-rev'd version of a common file, then swap it out.

Sorry for the confusion, and I'll gladly accept a PR if you feel up to it.

**Comment by regularmike** [comment]
I may take a look at it in a few weeks when I have some downtime. Do you use something else now to set up CDNs and fallbacks with gulp? I'm wondering how most people handle automating this when updating packages. I didn't find any other good solutions besides yours but I suppose people just roll their own functions.

**Comment by OverZealous** [comment]
My company is in the middle of building out a huge application (we're still in private beta), and we haven't even bothered worrying about switching on CDNs yet.  So, I haven't had much time to use my library.

This library is more popular than I would expect, but it is also the one giving me the most grief.  I'm have tempted to deprecate it just to keep people from asking for new features. ;-)
