### ISSUE TITLE
support node_modules

### ISSUE THREAD

**Issue by tcarlsen** [OverZealous/gulp-cdnizer#19]
Im starting on using npm to install my libraries as Angular and bootstrap instead of bower, but your package only looks for package version in the bower_components folder so I have to write the absolute cdn path.

This means that I need to remember to update my gulp file if I update my libraries, this is not a major big deal but an option to choice between searching in bower_components and node_modules would be awesome

**Comment by OverZealous** [comment]
I'm probably not going to be doing this any time soon, but you could easily write your own code to handle it, since gulp is just JavaScript.

I'm also willing to accept a PR.

**Comment by tcarlsen** [comment]
will take a look when I have time

**Comment by OverZealous** [comment]
Oh, hey, I just realized this is on here. I just rolled out a new version that supports this (v2.0), though I doubt you'll care nearly 3 years later! 😆

**Comment by tcarlsen** [comment]
I forgot this, but thx 😄
