### ISSUE TITLE
[QUESTION / ISSUE] Matchers not working

### ISSUE THREAD

**Issue by marocas** [OverZealous/gulp-cdnizer#22]
Hello there, 
I'm using your exemple to test your matcher option, and for me it isn't working.
Am I doing anything wrong, here is my code:

``` js
// gulp-cdnizer
gulp.task('cdnHtml', function(){
    gulp.src("./dist/**/*.*")
    .pipe(cdnizer({
        defaultCDNBase: absCDN,
        matchers: [
            // /(<a\s.*?href=.*?>)/gi,
            /(<img\s.*?data-src=["'])(.+?)(["'].*?>)/gi
        ],
        files: ['**/*.{gif,png,jpg,jpeg}', '*.html'],

    }))
    .pipe(gulp.dest("./dist"));

});
```

here i have my html:

``` html
<img data-src="/you/are/here.abc" alt="" >
```

Can you test it?

Thanks in advance, best regards Mário Silva.

**Comment by OverZealous** [comment]
There's not anything I can test there.

I don't use the custom matchers, they were added by a PR.  You can try updating the regex to look more [like the ones used in cdnizer itself](https://github.com/OverZealous/cdnizer/blob/master/lib/util.js#L40).

**Comment by OverZealous** [comment]
Also, you don't have any example output, so I don't even know what you mean by "it isn't working".

**Comment by marocas** [comment]
It was supposed to replace 
`<img data-src="/you/are/here.abc" alt="" />`
with
`<img data-src="http://somewebsite.com/you/are/here.abc" alt="" />`
but it doesn't

**Comment by tansj526** [comment]
hello, if I setting 
files: [
                '../css/**/*.css',
                '../js/**/*.js'
 ]
It not working, because the path have "../"
