### ISSUE TITLE
Not replacing parent directory relative paths

### ISSUE THREAD

**Issue by joshbaronmc** [OverZealous/gulp-cdnizer#23]
Hi, 

Thank you for creating gulp-cdnizer. I am having an issue with replacing CSS url() that have a parent directory relative path. My directory structure is:

build/dist/styles/default.style.css
build/dist/images/*

My gulp task is:

```
gulp.src(args.dest + 'styles/default.style.css')
	        .pipe(cdnizer([
	            {
	            	relativeRoot: 'dist/',
	                file: '**/*.png',
	                cdn: 'my.cdn/images/${ filename }'
	            }
	        ]))
	        .pipe(gulp.dest(args.dest + 'styles/'));
```

In my CSS, I have:
`background-image: url(../images/sprite.png);`

CDNizer will not replace the ../images/sprite.png. If I change my CSS to (use current directory relative path instead of parent directory relative path):

`background-image: url(./images/sprite.png);`

It works. So, for some reason CDNizer will not replace CSS URLs that have ../ but does work for URLs that have ./

Any ideas on how I can get CDNizer to replace URLs in CSS that have relative parent directory paths like background-image: url(../images/sprite.png)?

Thanks!

**Comment by OverZealous** [comment]
Please report issues with [cdnizer against that repo](https://github.com/OverZealous/cdnizer), this repo is only for the gulp plugin.

[This is a known issue, and I don't have a general fix for it at this time.](https://github.com/OverZealous/cdnizer/issues/20)  Minimatch (which is being used for pattern matching) doesn't work with relative paths.
