### ISSUE TITLE
angular libraries cdnized incorrectly

### ISSUE THREAD

**Issue by mr-const** [OverZealous/gulp-cdnizer#24]
I try to cdnize angular-messages library, but cdnizer reduces filename to simple angular and refuses to produce cdn link. When I request angular-messages.js explicitly, filename copied correctly, but link still is invalid.
here is a file description:
```
                {
                    file: '**/angular-messages/*.js',
                    cdn: 'cdnjs:angular-messages:${filenameMin}'
                },
```
And here is an output:
```
<script src="cdnjs:angular-messages:angular.min.js"></script>
```

**Comment by OverZealous** [comment]
Please post issues with `cdnizer` to that repo.  This repo is only for the gulp plugin.

That being said, [this has already been reported](https://github.com/OverZealous/cdnizer/issues/16).  There's a fix in that issue.
