### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by ebdrup** [OverZealous/gulp-cdnizer#26]
nodesecurity.io reports a problem in the current cdnizer v1.1.6. It's using an old unsafe version of semver in it's dependency tree.
```
Advisories

 	Regular Expression Denial of Service
Module	semver@2.2.1
Vulnerable	<4.3.2
Patched	>=4.3.2
Path	gulp-cdnizer@1.1.6 > cdnizer@1.1.5 > jsdelivr-cdn-data@0.1.1 > semver@2.2.1
```

**Comment by OverZealous** [comment]
Not much I can do about this—the `jsdelivr` packages hasn't been updated in a long time.

I appreciate security concerns, but it's not practical to expect this to be fixed or even fixable.

**Comment by ebdrup** [comment]
I tried creating a PR here: https://github.com/shahata/jsdelivr-cdn-data/pull/6
