### ISSUE TITLE
How to test if a css file is loaded?

### ISSUE THREAD

**Issue by Clan-Utility** [OverZealous/gulp-cdnizer#27]
It is easy to test if a js file is loaded, e.g.,

```
{
    file: 'bower_components/please-wait/build/please-wait.js',
    package: 'please-wait',
    test: 'window.pleaseWait',
    cdn: '//cdnjs.cloudflare.com/ajax/libs/please-wait/${ version }/please-wait.min.js'
  },
```

However, I could not figure out how to test css file

```
{
    file: 'bower_components/please-wait/build/please-wait.css',
    package: 'please-wait',
    // test: 'window.pleaseWait', // How to test .css?
    cdn: '//cdnjs.cloudflare.com/ajax/libs/please-wait/${ version }/please-wait.min.css'
  }
```

**Comment by OverZealous** [comment]
Hey there. As it says in the README, there's no built-in functionality for a non-JavaScript fallback. For CSS, especially, this would be difficult to solve in a generic way.

However, the `fallbackTest` can be customized per import, [which is described here in the docs](https://github.com/OverZealous/gulp-cdnizer#optionsfallbacktest). Just write a JS snippet to detect if your CSS is loaded properly, and if not, inject the local copy of the CSS instead.

**Comment by OverZealous** [comment]
Also, for future reference, these sort of questions belong on the (cdnizer repo)[https://github.com/OverZealous/cdnizer]—this repo is only for the Gulp plugin itself.
