### ISSUE TITLE
How do I alter the path of the fallbackTest?

### ISSUE THREAD

**Issue by computersarecool** [OverZealous/gulp-cdnizer#28]
Hi,
Because of the way my project is structured, my bower components before I run `cdnizer` are located up a directory, so all of the paths in my HTML look like:
`<script src="../bower_components/angular/angular.js"></script>`

but after, they are located in the same directory (so I would like the `../` part removed)

So when I run cdnizer with 
```
relativeRoot: __dirname,
bowerComponents: bower_components
```

Everything works in the cdn replacement but the fallback link is wrong. 

Is there a good way to change the path here? I tried adding this:
` fallbackTest: '<script>if(!(${ test })) cdnizerLoad("${ filepath.substr(3) }");</script>'` but that failed.

**Comment by OverZealous** [comment]
This is not really a task for cdnizer. You should correct this earlier in your build process. cdnizer is meant to replace the correct _local_ path with the correct cdn path.

**Comment by OverZealous** [comment]
Note that the test is just a template passed to lodash, so technically anything valid in a lodash template should work. But it's not really intended for complex replacements.

**Comment by computersarecool** [comment]
Thanks.
