### ISSUE TITLE
relativeRoot not working

### ISSUE THREAD

**Issue by yellow-sock** [OverZealous/gulp-cdnizer#7]
Hi,

thanks for gulp-cdnizer. Unfortunately it doesn't work for me.

My directory structure is:
```
./bower_components/angular/angular.js
./src/index.html
```
In index.html I have ```<script src="../bower_components/angular/angular.js"></script>```
Gulp task is:
```javascript
gulp.task('atest', ['clean'], function() {
gulp.src("./src/index.html")
    .pipe($.cdnizer({
      files: [{
          relativeRoot: 'src/',
          file: '../bower_components/angular/angular.js',
          package: 'angular',
          cdn: '//ajax.googleapis.com/ajax/libs/angularjs/${ version }/angular.min.js'
        }]
    }))
    .pipe(gulp.dest("./dist"));
});
```

Am I doing something wrong ? I am working on windows where the naming standard for path uses backslashes instead of slashes .. could that cause an issue ?

Thank you!

**Comment by OverZealous** [comment]
What are you getting as the output?

Note: I can't provide any support under Windows, so if it's a Windows issue, you'll have to track it down on your own.

**Comment by OverZealous** [comment]
Also, you are using it wrong: `relativeRoot` does **not** belong inside a file hash, it has no meaning there.  It's only used within the root options.

You also don't even need to worry about `relativeRoot` in your example, because you are replacing a file directly.  `relativeRoot` is only necessary if you are replacing multiple files and need the file name or file path as part of your output.  In your example, `cdnizer` should very simply find file references of `../bower_components/angular/angular.js` and replace them with `//ajax.googleapis.com/ajax/libs/angularjs/${ version }/angular.min.js`, where `${ version }` is the full version of Angular in your bower file.

Finally, you don't need to do any of this at all.  Simply replacing your entire block with this and it should work automatically as of v1.0:

```js
$.cdnizer([ 'google:angular' ])
```

**Comment by yellow-sock** [comment]
Thanks for the quick response.

The output I get is always empty .. something like:
```
[20:08:29] Using gulpfile d:\MyProject\gulpfile.js
[20:08:29] Starting 'clean'...
[20:08:29] Finished 'clean' after 35 ms
[20:08:29] Starting 'atest'...
[20:08:29] Finished 'atest' after 115 ms
```
I tried moving the relativeRoot up like you suggested with no success.
```
$.cdnizer({
      relativeRoot: 'src/',
        files: [{
          file: '../bower_components/angular/angular.js',
          cdn: '//ajax.googleapis.com/ajax/libs/angularjs/${ version }/angular.min.js'
        }]
    })
```

I added several path versions to my index.html file for testing:
```
<script src="angular.js"></script>
<script src="angular/angular.js"></script>
<script src="/angular/angular.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="/bower_components/angular/angular.js"></script>
<script src="../bower_components/angular/angular.js"></script>
<script src="src/bower_components/angular/angular.js"></script>
<script src="/src/bower_components/angular/angular.js"></script>
```
When I run 
```
gulp.task('cdnizer_test2', ['clean'], function() {
  gulp.src("./src/index.html")
    .pipe($.cdnizer([ 'google:angular' ]))
    .pipe(gulp.dest("./dist"));
});
```
with it I get 
```
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("angular.js");</script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("angular/angular.js");</script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("/angular/angular.js");</script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("bower_components/angular/angular.js");</script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("/bower_components/angular/angular.js");</script>
<script src="../bower_components/angular/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("src/bower_components/angular/angular.js");</script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("/src/bower_components/angular/angular.js");</script>
```
So only the relative version ../bower_components/angular/angular.js that I need is not working.

If there is anything you want me to test let me know.

**Comment by OverZealous** [comment]
OK, it looks like there's a bug in cdnizer's matching that simply won't match relative paths at all.

**Comment by OverZealous** [comment]
One thing, I haven't used `relativeRoot` so I forgot my own code.

It's not supposed to be something like `../`, instead it should be the URL root relative to the file.

For example, in your case, `relativeRoot` should be `'src/'`.  This means the name will resolve from `src/../bower_components/...` to `bower_components/...`.  This will fix the `google:angular` solution.  However, there is still a bug in the way `minimatch` works that completely prevents relative paths from matching.

**Comment by OverZealous** [comment]
After more testing, I've determined it is _not_ a bug in cdnizer or minimatch, simply that `relativeRoot` was set incorrectly.

Set `relativeRoot` to `src/` and you should be all set, no matter how you match the file.  Basically, you cannot use relative paths without a valid `relativeRoot`.

**Comment by yellow-sock** [comment]
Thanks that worked.

However 
```
gulp.task('cdnizer_test2', ['clean'], function() {
  gulp.src("./src/index.html")
    .pipe($.cdnizer({
      relativeRoot: 'css',
     files: [ 'google:angular' ]
    }))
    .pipe(gulp.dest("./dist"));
});
```
turns
```
<script src="../bower_components/angular/angular.js"></script>
<script src="../bower_components/angular-animate/angular-animate.js"></script>
<script src="../bower_components/angular-cookies/angular-cookies.js"></script>
<script src="../bower_components/angular-touch/angular-touch.js"></script>
<script src="../bower_components/angular-sanitize/angular-sanitize.js"></script>
<script src="../bower_components/angular-resource/angular-resource.js"></script>
<script src="../bower_components/angular-ui-router/release/angular-ui-router.js"></script>
```
into
```
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("../bower_components/angular/angular.js");</script>
<script src="../bower_components/angular-animate/angular-animate.js"></script>
<script src="../bower_components/angular-cookies/angular-cookies.js"></script>
<script src="../bower_components/angular-touch/angular-touch.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("../bower_components/angular-sanitize/angular-sanitize.js");</script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("../bower_components/angular-resource/angular-resource.js");</script>
<script src="../bower_components/angular-ui-router/release/angular-ui-router.js"></script>
```
resulting in 3 duplicate lines.
```

**Comment by yellow-sock** [comment]
I also cant easily work around this problem because
```
gulp.task('atest', ['clean'], function() {
  gulp.src("./src/index.html")
    .pipe($.cdnizer({
      relativeRoot: 'src/',
        files: [{
          file: '../bower_components/angular/angular.js',
          cdn: '//ajax.googleapis.com/ajax/libs/angularjs/${ version }/angular.min.js'
        }]
    }))
    .pipe(gulp.dest("./dist"));
});
```
applied to the same index.html as in my previous post doesn't change links. I think I used cdnizer correctly ?

**Comment by OverZealous** [comment]
OK, the problem is the matcher that revisioned files is catching those other forms.  If you don't use `gulp-rev`, you can simply add the top-level property `allowRev: false`, and you should be set.

**Comment by OverZealous** [comment]
Your example won't work because you have `../` in your file matcher, which gets removed.  Try just using `bower_components/...` without the relative path.

**Comment by OverZealous** [comment]
Yet another solution: include the additional resources (`angular-resource` and `angular-sanitize`) _above_ the `angular` resource in your files list, assuming you want them to come from the CDN:

```
$.cdnizer({
    relativeRoot: 'css/',
    files: [ 'google:angular-sanitize',  'google:angular-resource',  'google:angular']
})
```

This will ensure that they match first.

**Comment by yellow-sock** [comment]
The workaround that I found is to use the 'google:angular' style as you suggested and where this doesn't work like for bootstrap.js I use ** instead of .. in the file path:
```
gulp.task('cdnizer', ['clean'], function() {
  gulp.src("./src/index.html")
    .pipe($.cdnizer({
      relativeRoot: 'src/',
      allowRev: false,
     files: [
       'google:jquery',
       'cdnjs:modernizr',
       'google:angular',
       'google:angular-animate',
       'google:angular-cookies',
       'google:angular-touch',
       'google:angular-sanitize',
       'google:angular-resource',
       'cdnjs:angular-ui-router',
       {
         file: '**/bower_components/bootstrap/dist/js/bootstrap.js',
         package: 'bootstrap',
         cdn: '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/${ version }/bootstrap.min.js'
       },
       'cdnjs:d3' ]
    }))
    .pipe(gulp.dest("./dist"));
});
```
It does however look like a bug that relative paths don't work.

Thanks a lot for your help. Much appreciated!

**Comment by yellow-sock** [comment]
Just a site-note. Relative paths for java script like ```<script src="../bower_components/angular/angular.js">```</script>"  in index.html are created by a generator [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) which uses Google's [Best Practice Recommendations for Angular App Structure](https://docs.google.com/a/ruscha.de/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub). It should not be just me using relative references. 
Would be nice if generator-gulp-angular would include cdnizer as an option but I just read that they don't want to add any more features for the 1.0 release.
