### ISSUE TITLE
how to remove all cdn prefix?

### ISSUE THREAD

**Issue by shanelau** [OverZealous/gulp-cdnizer#8]
I deal all my file by gulp-cdnizer，It works awesome !

All  links  have a prefix，How can I remove all CDN prefix?

**Comment by OverZealous** [comment]
I don't know what you mean.  It only modifies files that match the patterns you provide.  If you don't want the prefix, then specify which files you want modified.

**Comment by shanelau** [comment]
In a development environment，I  need to test all cdn file ,when test finish .I don't need CDN prefix any more, all file keep relative url  would be fine

**Comment by OverZealous** [comment]
Are you overwriting your source files?  That's a huge mistake, not my problem.  gulp-cdnizer should be called when you build your source files for production, usually after you concatenate and minify them.

This has nothing to do with gulp-cdnizer.
